In [1]:
# Importing Necessary Libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df_movies = pd.read_csv("../../data/movie-review-data/rotten_tomatoes_movies.csv")
df_movies.head(2).T

                                               0                1
id                            space-zombie-bingo  the_green_grass
title                        Space Zombie Bingo!  The Green Grass
audienceScore                               50.0              NaN
tomatoMeter                                  NaN              NaN
rating                                       NaN              NaN
ratingContents                               NaN              NaN
releaseDateTheaters                          NaN              NaN
releaseDateStreaming                  2018-08-25       2020-02-11
runtimeMinutes                              75.0            114.0
genre                     Comedy, Horror, Sci-fi            Drama
originalLanguage                         English          English
director                           George Ormrod  Tiffany Edwards
writer                George Ormrod,John Sabotta  Tiffany Edwards
boxOffice                                    NaN              NaN
distributor                                  NaN              NaN
soundMix                                     NaN              NaN

In [3]:
null_percentage = df_movies.isnull().mean() * 100
null_percentage_df = null_percentage.sort_values(ascending=False).to_frame(name='MissingPercent')
null_percentage_df

                      MissingPercent
ratingContents             90.233704
rating                     90.233704
boxOffice                  89.708777
soundMix                   88.889277
distributor                83.944352
releaseDateTheaters        78.519175
tomatoMeter                76.352455
audienceScore              48.869871
releaseDateStreaming       44.561560
writer                     37.095311
originalLanguage            9.673456
runtimeMinutes              9.651817
genre                       7.736392
director                    2.943640
title                       0.256181
id                          0.000000

In [4]:
df_movies.drop(columns=['audienceScore', 'tomatoMeter', 'rating', 'ratingContents', 'releaseDateTheaters', 'boxOffice', 'distributor', 'soundMix'], inplace=True)
df_movies.sample(3).T

,127672,142892,92546
id,deadly_snail_vs_kung_fu_killer,wednesday_1997,high_ground_2021
title,Deadly Snail vs. Kung Fu Killer,Sreda,High Ground
releaseDateStreaming,2015-08-07,NaN,2021-05-14
runtimeMinutes,88.0,NaN,104.0
genre,Adventure,NaN,"Adventure, Drama"
originalLanguage,English,NaN,English (Australia)
director,Ling Shang,Victor Kossakovsky,Stephen Johnson
writer,Ling Shang,NaN,Chris Anastassiades

In [5]:
df_movies['genre'].value_counts()

genre
Drama                                                            27860
Documentary                                                      15162
Comedy                                                           11514
Mystery & thriller                                                7015
Comedy, Drama                                                     5479
                                                                 ...
Action, Comedy, Fantasy, Horror, Sci-fi                              1
Documentary, Lgbtq+, Drama                                           1
Kids & family, Holiday, Musical, Comedy, Adventure, Animation        1
Drama, Romance, Sports & fitness                                     1
Crime, Documentary, History, Sports & fitness                        1
Name: count, Length: 2912, dtype: int64

In [6]:
df_movies['genre'] = df_movies['genre'].apply(
    lambda x: [g.strip().lower() for g in x.split(",")] if isinstance(x, str) else x
)
df_movies['genre'].value_counts()

genre
[drama]                                                            27860
[documentary]                                                      15162
[comedy]                                                           11514
[mystery & thriller]                                                7015
[comedy, drama]                                                     5479
                                                                   ...
[action, comedy, fantasy, horror, sci-fi]                              1
[documentary, lgbtq+, drama]                                           1
[kids & family, holiday, musical, comedy, adventure, animation]        1
[drama, romance, sports & fitness]                                     1
[crime, documentary, history, sports & fitness]                        1
Name: count, Length: 2912, dtype: int64

In [7]:
df_movies.to_csv('../../data/movie-review-data/transformed_movies.csv', index=False)